#!/bin/bash 

if [[ -z "$ISR_HOME" || ! -d "$ISR_HOME" ]]; then
	echo "ISR_HOME variable is not set"
	exit 1
fi
if [[ ! -r "$ISR_HOME/isr.conf" ]]; then
	echo "ISR_HOME not set properly. Cannot find isr.conf"
	exit 1
fi

. $ISR_HOME/isr.conf
. $ISR_HOME/scripts/functions.sh


if [ $# -lt 1 ]; then
	echo "Usage: $0 executable_file"
	exit 1
fi

if [ ! -r $1 ]; then
	echo "Cannot find $1, or not readable"
	exit 1
fi

# Add the binary
$ISR_HOME/scripts/isrencode $1

# Add all its dependencies
$ISR_HOME/scripts/isrdepsencode $1

