#!/bin/bash 


if [[ -z "$THERING_HOME" || ! -d "$THERING_HOME" ]]; then
	echo "THERING_HOME variable is not set"
	exit 1
fi
if [[ ! -r "$THERING_HOME/thering.conf" ]]; then
	echo "THERING_HOME not set properly. Cannot find thering.conf"
	exit 1
fi

. $THERING_HOME/thering.conf
. $THERING_HOME/scripts/functions.sh


self_path=`which $0 2> /dev/null`
self_dir=`dirname $self_path`

#echo "$self_dir/isrencode -d $THERING_HOME $*"
$self_dir/isrencode -d $ENCLIB $*

