#!/bin/bash 


if [[ -z "$ISR_HOME" || ! -d "$ISR_HOME" ]]; then
	echo "ISR_HOME variable is not set"
	exit 1
fi
if [[ ! -r "$ISR_HOME/isr.conf" ]]; then
	echo "ISR_HOME not set properly. Cannot find isr.conf"
	exit 1
fi

. $ISR_HOME/isr.conf
. $ISR_HOME/scripts/functions.sh


self_path=`which $0 2> /dev/null`
self_dir=`dirname $self_path`

#echo "$self_dir/isrencode -d $ISR_HOME $*"
$self_dir/isrencode -d $ENCLIB $*

