#!/bin/bash 

if [[ -z "$ISR_HOME" || ! -d "$ISR_HOME" ]]; then
	echo "ISR_HOME variable is not set"
	exit 1
fi
if [[ ! -r "$ISR_HOME/isr.conf" ]]; then
	echo "ISR_HOME not set properly. Cannot find isr.conf"
	exit 1
fi

. $ISR_HOME/isr.conf
. $ISR_HOME/scripts/functions.sh


if [ $# -lt 1 ]; then
	echo "Usage: $0 file [file] ..."
	exit 1
fi


function remove_file {
	if [ ! -f "$1" ]; then
		echo "$1 not found, will be just deleted from database!"
	fi

	# Remove key from DB
	sqlstmt="delete from image where path='$1';"

	#echo $SQLITE $DBFILE "$sqlstmt"
	$SQLITE $DBFILE "$sqlstmt" || exit 1

	# Delete file
	rm -f "$1"
}

while [ ! -z "$1" ]; do
    path=`readlink -f $1`
    #echo "Removing $path"


	remove_file $path
	echo "$path [Deleted]"
	shift 1
done


